---
language: rust
rust:
    - beta
    - stable
    - nightly

matrix:
    allow_failures:
        - rust:
            - nightly
            - beta

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y texinfo

notifications:
    email: false

branches:
    only:
        - master
